CREATE TABLE IF NOT EXISTS rooms (
 id TEXT PRIMARY KEY NOT NULL,
 state TEXT NOT NULL,
 revision INTEGER NOT NULL DEFAULT 0,
 expires INTEGER NOT NULL,
 seen0 INTEGER NOT NULL DEFAULT 0,
 seen1 INTEGER NOT NULL DEFAULT 0
);
