'use client';
import { useEffect, useReducer, useRef, useState } from 'react';
import { Dices, BookOpen, RotateCcw, Shield, Crown, ArrowRight, Check, X } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
import DiceTable from '@/components/dice-table';
import { gameReducer, initialGame, scoreDice, bestSelection, playerName, type Mode, type Game } from '@/lib/game';
const number=(n:number)=>n.toLocaleString('uk-UA');
const pipSymbols=['','⚀','⚁','⚂','⚃','⚄','⚅'];
export default function Home(){
 const [game,dispatch]=useReducer(gameReducer,undefined,()=>initialGame());
 const [rules,setRules]=useState(false),[newMode,setNewMode]=useState<Mode|null>(null);
 const gameRef=useRef(game);gameRef.current=game;
 const isBot=game.mode==='bot'&&game.player===1;
 const selectedScore=scoreDice(game.selected.map(i=>game.dice[i]));
 const canChoose=game.phase==='choose'&&!isBot;
 const nextName=playerName(game,1-game.player);
 const selectedInvalid=game.selected.length>0&&!selectedScore;
 const fresh=game.scores.every(n=>n===0)&&game.phase==='ready'&&game.round===1&&game.player===0;
 const requestNew=(mode:Mode)=>{if(fresh)dispatch({type:'new',mode});else setNewMode(mode);};
 useEffect(()=>{
  if(game.mode!=='bot'||rules||newMode)return;
  let fn:(()=>void)|undefined;
  if(game.phase==='handoff'||game.phase==='bust')fn=()=>dispatch({type:'next'});
  else if(isBot&&game.phase==='ready')fn=()=>dispatch({type:'roll'});
  else if(isBot&&game.phase==='choose'){
   if(!game.selected.length)fn=()=>dispatch({type:'select',ids:bestSelection(game.dice,game.locked).ids});
   else{const total=game.pot+selectedScore;const remaining=6-game.locked.length-game.selected.length;const winning=game.scores[1]+total>=4000;const stop=winning||total>=700||(remaining<=2&&remaining>0&&total>=300);fn=()=>dispatch({type:stop?'bank':'roll'});}
  }
  if(fn){const id=setTimeout(fn,game.phase==='bust'?2400:game.phase==='handoff'?1600:1100);return ()=>clearTimeout(id);}
 },[game,isBot,selectedScore,rules,newMode]);
 // Optional browser-agent readback uses exactly the same game state.
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:'read_farkle_game',title:'Read the current Farkle game',description:'Read scores, active player, dice, held dice and the current turn phase.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');const g=gameRef.current;return {mode:g.mode,phase:g.phase,player:playerName(g),scores:g.scores,turnPoints:g.pot,dice:g.dice,selected:g.selected,locked:g.locked,target:4000};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return ()=>lifecycle.abort();
 },[]);
 let instruction=game.message;
 if(game.phase==='choose')instruction=isBot?'Корчмар обмірковує наступний кидок…':selectedInvalid?'У виборі є кубики, що не дають очок.':selectedScore?`Вибрано: +${number(selectedScore)}. Забрати чи ризикнути?`:'Натисніть на кубики, що дають очки.';
 if(game.phase==='ready'&&isBot)instruction='Корчмар готується кидати…';
 return <main className="tavern"><header className="masthead"><div className="brand"><Dices size={30}/><div><h1>Корчма</h1><span>FARKLE · ГРА В КОСТІ</span></div></div><nav aria-label="Меню гри"><button className="quiet" onClick={()=>setRules(true)}><BookOpen size={17}/> Правила</button><button className="quiet" onClick={()=>requestNew(game.mode)}><RotateCcw size={17}/> Нова гра</button></nav></header>
 <div className="game-layout"><section className="play-column" aria-label="Ігровий стіл"><div className="table-heading"><span className="eyebrow">СТІЛ № 01 <span className="round"> / РАУНД {game.round}</span></span><span>Партія до <b>4 000</b></span></div>
 <div className="scores">{[0,1].map((p)=><PlayerScore key={p} game={game} p={p}/>)}</div>
 <div className={'board '+(game.phase==='rolling'?'rolling':'')}><div className="board-label">{game.phase==='rolling'?'ЩАСТЯ ВЖЕ НА СТОЛІ':game.locked.length?'ВІДКЛАДЕНІ КУБИКИ — БІЛЯ ДАЛЬНЬОГО КРАЮ':'НЕХАЙ ЩАСТИТЬ'}</div><DiceTable game={game} interactive={canChoose} onSelect={id=>dispatch({type:'toggle',id})} onResult={(values,rollId)=>dispatch({type:'rolled',values,rollId})}/>
 {(game.phase==='bust'||game.phase==='won'||(game.phase==='handoff'&&game.mode==='hotseat'))&&<div className="table-overlay"><div className="table-notice"><span className="eyebrow">{game.phase==='bust'?'FARKLE':game.phase==='won'?'ПАРТІЮ ЗАВЕРШЕНО':'ПЕРЕДАЙТЕ ПРИСТРІЙ'}</span><h2>{game.phase==='bust'?'Удача відвернулась':game.phase==='won'?`${playerName(game)} — перемога!`:`Хід: ${nextName}`}</h2><p>{game.phase==='won'?`Переможний рахунок — ${number(game.scores[game.player])}.` :game.message}</p>{game.phase==='won'?<button className="primary" onClick={()=>dispatch({type:'new',mode:game.mode})}>Зіграти ще раз <RotateCcw size={16}/></button>:game.mode==='hotseat'?<button className="primary" onClick={()=>dispatch({type:'next'})}>{game.phase==='bust'?`Передати хід: ${nextName}`:'Готовий до кидка'}<ArrowRight size={16}/></button>:<span className="waiting">Наступний хід…</span>}</div></div>}
 {game.phase==='ready'&&<p className="board-caption">Шість кубиків. Один вдалий кидок.</p>}</div>
 <div className="dice-strip" aria-label="Результати кубиків">{game.dice.map((v,i)=><button key={i} className={'die-button '+(game.selected.includes(i)?'selected ':'')+(game.locked.includes(i)?'locked':'')} aria-label={`Кубик ${i+1}: ${v}${game.locked.includes(i)?', відкладений':''}`} aria-pressed={game.selected.includes(i)} disabled={!canChoose||game.locked.includes(i)} onClick={()=>dispatch({type:'toggle',id:i})}><span aria-hidden="true">{pipSymbols[v]}</span>{game.locked.includes(i)?<Check size={12}/>:<small>{i+1}</small>}</button>)}<span className="dice-strip-hint">{game.phase==='rolling'?'Кубики котяться…':game.locked.length?`Відкладено ${game.locked.length} із 6`:'Вибирайте на столі або тут'}</span></div>
 <section className="turn-panel"><div className="turn-total"><span className="eyebrow">ОЧКИ ЗА ХІД</span><strong className="turn-score">{number(game.pot+selectedScore)}</strong>{selectedScore>0&&<span className="selection-score">з них +{number(selectedScore)} вибрано</span>}</div><div className="turn-action"><p aria-live="polite" className={selectedInvalid?'invalid':''}>{instruction}</p><div className="action-buttons">{game.phase==='ready'&&!isBot&&<button className="primary" onClick={()=>dispatch({type:'roll'})}><Dices size={19}/> Кинути кубики</button>}{game.phase==='choose'&&!isBot&&<><button className="secondary" disabled={!selectedScore} onClick={()=>dispatch({type:'roll'})}><Dices size={18}/>{game.selected.length+game.locked.length===6?'Кинути всі 6':'Кинути ще'}</button><button className="primary" disabled={!selectedScore} onClick={()=>dispatch({type:'bank'})}>Забрати {number(game.pot+selectedScore)} <Check size={17}/></button></>}{(game.phase==='rolling'||isBot&&game.phase!=='won')&&<span className="waiting"><span className="status-dot"/>{game.phase==='rolling'?'Кидаємо…':'Хід корчмаря'}</span>}</div></div></section>
 </section><aside className="sidebar"><div className="side-block"><span className="eyebrow">З КИМ ГРАЄМО?</span><button aria-pressed={game.mode==='bot'} className={'mode '+(game.mode==='bot'?'chosen':'')} onClick={()=>game.mode!=='bot'&&requestNew('bot')}><Crown/><span>Проти корчмаря<small>Комп’ютерний суперник</small></span>{game.mode==='bot'&&<span className="mode-dot"/>}</button><button aria-pressed={game.mode==='hotseat'} className={'mode '+(game.mode==='hotseat'?'chosen':'')} onClick={()=>game.mode!=='hotseat'&&requestNew('hotseat')}><Shield/><span>Удвох за столом<small>Один пристрій · по черзі</small></span>{game.mode==='hotseat'&&<span className="mode-dot"/>}</button></div>
 <div className="side-block"><span className="eyebrow">ВАРТІСТЬ КОМБІНАЦІЙ</span><div className="rule-row"><span><i>⚀</i> Одиниця</span><b>100</b></div><div className="rule-row"><span><i>⚄</i> П’ятірка</span><b>50</b></div><div className="rule-row"><span>Три одиниці</span><b>1 000</b></div><div className="rule-row"><span>Три однакові</span><b>грань × 100</b></div><button className="rules-link" onClick={()=>setRules(true)}>Усі комбінації <ArrowRight size={14}/></button><p className="tip">Забрати очки чи ризикнути ще раз? У цьому вся гра.</p></div><div className="tavern-note">«Удача любить сміливих.<br/>Але борги пам’ятає корчмар.»<span>— за сусіднім столом</span></div></aside></div><footer>Звичайні кубики <span>◆</span> Чесна гра</footer>
 <Dialog open={rules} onOpenChange={setRules}><DialogContent className="game-dialog" showCloseButton={false}><DialogClose className="dialog-close" aria-label="Закрити правила"><X size={20}/></DialogClose><DialogTitle className="dialog-title">Правила корчми</DialogTitle><DialogDescription>Перший, хто набере 4 000 очок, перемагає.</DialogDescription><div className="rules-body"><p>Киньте шість кубиків. Виберіть хоча б одну залікову комбінацію, а потім заберіть очки або киньте решту кубиків ще раз.</p><div className="rule-row"><span>Одна 1 / одна 5</span><b>100 / 50</b></div><div className="rule-row"><span>Три 1</span><b>1 000</b></div><div className="rule-row"><span>Три 2, 3, 4, 5 або 6</span><b>200–600</b></div><div className="rule-row"><span>Кожен наступний однаковий</span><b>подвоює комбінацію</b></div><div className="rule-row"><span>1–2–3–4–5</span><b>500</b></div><div className="rule-row"><span>2–3–4–5–6</span><b>750</b></div><div className="rule-row"><span>1–2–3–4–5–6</span><b>1 500</b></div><p><b>Невдалий кидок:</b> якщо жоден кубик не дає очок, усі незабрані очки цього ходу згорають. Загальний рахунок залишається.</p><p><b>Усі шість залікові?</b> Можна знову кинути всі шість і продовжити накопичувати очки.</p><p>Комбінації складаються тільки з одного кидка. Відкладені кубики не можна додати до нової комбінації.</p><DialogClose className="primary">До столу</DialogClose></div></DialogContent></Dialog>
 <Dialog open={newMode!==null} onOpenChange={open=>{if(!open)setNewMode(null);}}><DialogContent className="game-dialog" showCloseButton={false}><DialogTitle className="dialog-title">Почати нову партію?</DialogTitle><DialogDescription>Поточний рахунок буде скинуто. Режим: {newMode==='bot'?'проти корчмаря':'удвох на одному пристрої'}.</DialogDescription><div className="dialog-actions"><button className="secondary" onClick={()=>setNewMode(null)}>Продовжити гру</button><button className="primary" onClick={()=>{dispatch({type:'new',mode:newMode!});setNewMode(null);}}>Нова партія</button></div></DialogContent></Dialog>
 </main>
}
function PlayerScore({game,p}:{game:Game;p:number}){const active=game.player===p;return <><div className={'player '+(active?'active':'')} aria-label={`${playerName(game,p)}: ${game.scores[p]} очок${active?', поточний хід':''}`}>{p===0?<Shield/>:<Crown/>}<div><span>{playerName(game,p)}</span><strong>{number(game.scores[p])}</strong></div>{active&&<small>{game.phase==='won'?'ПЕРЕМОГА':'ЗАРАЗ ГРАЄ'}</small>}<div className="score-track"><div style={{width:`${Math.min(100,game.scores[p]/4000*100)}%`}}/></div></div>{p===0&&<span className="versus">VS</span>}</>}
